// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

contract C {
  function ui8() private returns (uint256) { return 42; }
  function ui256() private returns (uint256) { return 57896044618658097711785492504343953926634992332820282019728792003956564819968; }
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: module {
// CHECK-NEXT:   sol.contract @C_17 {
// CHECK-NEXT:     sol.func @ui8_8() -> ui256 attributes {state_mutability = #sol<StateMutability NonPayable>} {
// CHECK-NEXT:       %c42_ui8 = sol.constant 42 : ui8 loc(#loc3)
// CHECK-NEXT:       %0 = sol.ext %c42_ui8 : ui8 to ui256 loc(#loc3)
// CHECK-NEXT:       sol.return %0 : ui256 loc(#loc4)
// CHECK-NEXT:     } loc(#loc2)
// CHECK-NEXT:     sol.func @ui256_16() -> ui256 attributes {state_mutability = #sol<StateMutability NonPayable>} {
// CHECK-NEXT:       %c-57896044618658097711785492504343953926634992332820282019728792003956564819968_ui256 = sol.constant 57896044618658097711785492504343953926634992332820282019728792003956564819968 : ui256 loc(#loc6)
// CHECK-NEXT:       sol.return %c-57896044618658097711785492504343953926634992332820282019728792003956564819968_ui256 : ui256 loc(#loc7)
// CHECK-NEXT:     } loc(#loc5)
// CHECK-NEXT:   } {interface_fns = [], kind = #sol<ContractKind Contract>} loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:3:2)
// CHECK-NEXT: #loc3 = loc({{.*}}:3:52)
// CHECK-NEXT: #loc4 = loc({{.*}}:3:45)
// CHECK-NEXT: #loc5 = loc({{.*}}:4:2)
// CHECK-NEXT: #loc6 = loc({{.*}}:4:54)
// CHECK-NEXT: #loc7 = loc({{.*}}:4:47)
// CHECK-EMPTY:
