// RUN: solc --mlir-action=print-init %s | FileCheck %s
// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck --check-prefix=DBG %s

contract C {
}
contract D {
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: module {
// CHECK-NEXT:   sol.contract @C {
// CHECK-NEXT:   }
// CHECK-NEXT:   sol.contract @D {
// CHECK-NEXT:   }
// CHECK-NEXT: }
// CHECK-EMPTY:
// DBG: module {
// DBG-NEXT:   sol.contract @C {
// DBG-NEXT:   } loc(#loc1)
// DBG-NEXT:   sol.contract @D {
// DBG-NEXT:   } loc(#loc2)
// DBG-NEXT: } loc(#loc0)
// DBG-NEXT: #loc0 = loc(unknown)
// DBG-NEXT: #loc1 = loc({{.*}}:3:0)
// DBG-NEXT: #loc2 = loc({{.*}}:5:0)
// DBG-EMPTY:
