// RUN: solc --mlir --yul %s | FileCheck %s

{
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: module {
// CHECK-NEXT:   solidity.yul_block {
// CHECK-NEXT:   }
// CHECK-NEXT: }
