// RUN: solc --yul --mlir %s | FileCheck %s
// RUN: solc --yul --mlir --mmlir --mlir-print-debuginfo %s | FileCheck --check-prefix=DBG %s

{
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: module {
// CHECK-NEXT:   solidity.object @object {
// CHECK-NEXT:   }
// CHECK-NEXT: }
// DBG: module {
// DBG-NEXT:   solidity.object @object {
// DBG-NEXT:   } loc(#loc)
// DBG-NEXT: } loc(#loc)
// DBG-NEXT: #loc = loc(unknown)
