// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

function power(uint256 base, uint256 exponent) pure returns (uint256) {
  unchecked {
    return base ** exponent;
  }
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Prague = #sol<EvmVersion Prague>
// CHECK-NEXT: #Pure = #sol<StateMutability Pure>
// CHECK-NEXT: #loc2 = loc({{.*}}:2:15)
// CHECK-NEXT: #loc3 = loc({{.*}}:2:29)
// CHECK-NEXT: module attributes {sol.evm_version = #Prague} {
// CHECK-NEXT:   sol.func @power_15(%arg0: ui256 loc({{.*}}:2:15), %arg1: ui256 loc({{.*}}:2:29)) -> ui256 attributes {state_mutability = #Pure} {
// CHECK-NEXT:     %0 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc2)
// CHECK-NEXT:     sol.store %arg0, %0 : ui256, !sol.ptr<ui256, Stack> loc(#loc2)
// CHECK-NEXT:     %1 = sol.alloca : !sol.ptr<ui256, Stack> loc(#loc3)
// CHECK-NEXT:     sol.store %arg1, %1 : ui256, !sol.ptr<ui256, Stack> loc(#loc3)
// CHECK-NEXT:     %2 = sol.load %0 : !sol.ptr<ui256, Stack>, ui256 loc(#loc4)
// CHECK-NEXT:     %3 = sol.load %1 : !sol.ptr<ui256, Stack>, ui256 loc(#loc5)
// CHECK-NEXT:     %4 = sol.exp %2, %3 : ui256 loc(#loc4)
// CHECK-NEXT:     sol.return %4 : ui256 loc(#loc6)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc4 = loc({{.*}}:4:11)
// CHECK-NEXT: #loc5 = loc({{.*}}:4:19)
// CHECK-NEXT: #loc6 = loc({{.*}}:4:4)
// CHECK-EMPTY:
