// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

contract C {
	function inp_ui(uint a) public returns (uint) { return internal_inp_ui(a); }
	function internal_inp_ui(uint a) internal returns (uint) { return a; }
	function out_bool() public returns (bool) { return true; }
	function out_ui() public returns (uint) { return 42; }

	function inp_string(string memory a) public { internal_inp_string(a); }
	function internal_inp_string(string memory a) internal {}
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #loc3 = loc({{.*}}:3:17)
// CHECK-NEXT: #loc8 = loc({{.*}}:4:26)
// CHECK-NEXT: #loc18 = loc({{.*}}:8:21)
// CHECK-NEXT: #loc22 = loc({{.*}}:9:30)
// CHECK-NEXT: module {
// CHECK-NEXT:   sol.contract @C_55 {
// CHECK-NEXT:     sol.func @inp_ui_12(%arg0: i256 loc({{.*}}:3:17)) -> i256 attributes {state_mutability = #sol<StateMutability NonPayable>} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<i256, Stack> loc(#loc3)
// CHECK-NEXT:       sol.store %arg0, %0 : i256, !sol.ptr<i256, Stack> loc(#loc3)
// CHECK-NEXT:       %1 = sol.load %0 : !sol.ptr<i256, Stack>, i256 loc(#loc4)
// CHECK-NEXT:       %2 = sol.call @internal_inp_ui_22(%1) : (i256) -> i256 loc(#loc5)
// CHECK-NEXT:       sol.return %2 : i256 loc(#loc6)
// CHECK-NEXT:     } loc(#loc2)
// CHECK-NEXT:     sol.func @internal_inp_ui_22(%arg0: i256 loc({{.*}}:4:26)) -> i256 attributes {state_mutability = #sol<StateMutability NonPayable>} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<i256, Stack> loc(#loc8)
// CHECK-NEXT:       sol.store %arg0, %0 : i256, !sol.ptr<i256, Stack> loc(#loc8)
// CHECK-NEXT:       %1 = sol.load %0 : !sol.ptr<i256, Stack>, i256 loc(#loc9)
// CHECK-NEXT:       sol.return %1 : i256 loc(#loc10)
// CHECK-NEXT:     } loc(#loc7)
// CHECK-NEXT:     sol.func @out_bool_30() -> i1 attributes {state_mutability = #sol<StateMutability NonPayable>} {
// CHECK-NEXT:       %true = arith.constant true loc(#loc12)
// CHECK-NEXT:       sol.return %true : i1 loc(#loc13)
// CHECK-NEXT:     } loc(#loc11)
// CHECK-NEXT:     sol.func @out_ui_38() -> i256 attributes {state_mutability = #sol<StateMutability NonPayable>} {
// CHECK-NEXT:       %c42_i8 = arith.constant 42 : i8 loc(#loc15)
// CHECK-NEXT:       %0 = arith.extui %c42_i8 : i8 to i256 loc(#loc15)
// CHECK-NEXT:       sol.return %0 : i256 loc(#loc16)
// CHECK-NEXT:     } loc(#loc14)
// CHECK-NEXT:     sol.func @inp_string_48(%arg0: !sol.string<Memory> loc({{.*}}:8:21)) attributes {state_mutability = #sol<StateMutability NonPayable>} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.string<Memory>, Stack> loc(#loc18)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.string<Memory>, !sol.ptr<!sol.string<Memory>, Stack> loc(#loc18)
// CHECK-NEXT:       %1 = sol.load %0 : !sol.ptr<!sol.string<Memory>, Stack>, !sol.string<Memory> loc(#loc19)
// CHECK-NEXT:       sol.call @internal_inp_string_54(%1) : (!sol.string<Memory>) -> () loc(#loc20)
// CHECK-NEXT:       sol.return loc(#loc17)
// CHECK-NEXT:     } loc(#loc17)
// CHECK-NEXT:     sol.func @internal_inp_string_54(%arg0: !sol.string<Memory> loc({{.*}}:9:30)) attributes {state_mutability = #sol<StateMutability NonPayable>} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.string<Memory>, Stack> loc(#loc22)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.string<Memory>, !sol.ptr<!sol.string<Memory>, Stack> loc(#loc22)
// CHECK-NEXT:       sol.return loc(#loc21)
// CHECK-NEXT:     } loc(#loc21)
// CHECK-NEXT:   } {interface_fns = [{selector = 1891873197 : i32, sym = @out_bool_30, type = () -> i1}, {selector = 1913244289 : i32, sym = @inp_string_48, type = (!sol.string<Memory>) -> ()}, {selector = -1856136386 : i32, sym = @inp_ui_12, type = (i256) -> i256}, {selector = -597758925 : i32, sym = @out_ui_38, type = () -> i256}], kind = #sol<ContractKind Contract>} loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:3:1)
// CHECK-NEXT: #loc4 = loc({{.*}}:3:72)
// CHECK-NEXT: #loc5 = loc({{.*}}:3:56)
// CHECK-NEXT: #loc6 = loc({{.*}}:3:49)
// CHECK-NEXT: #loc7 = loc({{.*}}:4:1)
// CHECK-NEXT: #loc9 = loc({{.*}}:4:67)
// CHECK-NEXT: #loc10 = loc({{.*}}:4:60)
// CHECK-NEXT: #loc11 = loc({{.*}}:5:1)
// CHECK-NEXT: #loc12 = loc({{.*}}:5:52)
// CHECK-NEXT: #loc13 = loc({{.*}}:5:45)
// CHECK-NEXT: #loc14 = loc({{.*}}:6:1)
// CHECK-NEXT: #loc15 = loc({{.*}}:6:50)
// CHECK-NEXT: #loc16 = loc({{.*}}:6:43)
// CHECK-NEXT: #loc17 = loc({{.*}}:8:1)
// CHECK-NEXT: #loc19 = loc({{.*}}:8:67)
// CHECK-NEXT: #loc20 = loc({{.*}}:8:47)
// CHECK-NEXT: #loc21 = loc({{.*}}:9:1)
// CHECK-EMPTY:
