// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

// SPDX-License-Identifier: GPL-3.0

contract C {
  function f() public view returns (address) {
    return msg.sender;
  }
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: module {
// CHECK-NEXT:   sol.contract @C_10 {
// CHECK-NEXT:     sol.func @f_9() -> i256 attributes {state_mutability = #sol<StateMutability View>} {
// CHECK-NEXT:       %0 = sol.caller loc(#loc3)
// CHECK-NEXT:       sol.return %0 : i256 loc(#loc4)
// CHECK-NEXT:     } loc(#loc2)
// CHECK-NEXT:   } {interface_fns = [{selector = "26121ff0", sym = @f_9, type = () -> i256}], kind = #sol<ContractKind Contract>} loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:4:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:5:2)
// CHECK-NEXT: #loc3 = loc({{.*}}:6:11)
// CHECK-NEXT: #loc4 = loc({{.*}}:6:4)
// CHECK-EMPTY:
