// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

contract C {
  function msgSender() public view returns (address) {
    return msg.sender;
  }
  function addr() public view returns (address) {
    return address(0);
  }
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: module {
// CHECK-NEXT:   sol.contract @C_21 {
// CHECK-NEXT:     sol.func @msgSender_9() -> i256 attributes {state_mutability = #sol<StateMutability View>} {
// CHECK-NEXT:       %0 = sol.caller loc(#loc3)
// CHECK-NEXT:       sol.return %0 : i256 loc(#loc4)
// CHECK-NEXT:     } loc(#loc2)
// CHECK-NEXT:     sol.func @addr_20() -> i256 attributes {state_mutability = #sol<StateMutability View>} {
// CHECK-NEXT:       %c0_i8 = arith.constant 0 : i8 loc(#loc6)
// CHECK-NEXT:       %0 = arith.extui %c0_i8 : i8 to i256 loc(#loc6)
// CHECK-NEXT:       sol.return %0 : i256 loc(#loc7)
// CHECK-NEXT:     } loc(#loc5)
// CHECK-NEXT:   } {interface_fns = [{selector = "767800de", sym = @addr_20, type = () -> i256}, {selector = "d737d0c7", sym = @msgSender_9, type = () -> i256}], kind = #sol<ContractKind Contract>} loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:3:2)
// CHECK-NEXT: #loc3 = loc({{.*}}:4:11)
// CHECK-NEXT: #loc4 = loc({{.*}}:4:4)
// CHECK-NEXT: #loc5 = loc({{.*}}:6:2)
// CHECK-NEXT: #loc6 = loc({{.*}}:7:19)
// CHECK-NEXT: #loc7 = loc({{.*}}:7:4)
// CHECK-EMPTY:
