// RUN: solc --yul --mlir %s | FileCheck %s
// RUN: solc --yul --mlir --mmlir --mlir-print-debuginfo %s | FileCheck --check-prefix=DBG %s

object "Foo" {
  code {}
  object "Foo_deployed" {
    code {}
  }
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: module {
// CHECK-NEXT:   solidity.object @Foo {
// CHECK-NEXT:     solidity.yul_block {
// CHECK-NEXT:       solidity.yul_block {
// CHECK-NEXT:         solidity.object @Foo_deployed {
// CHECK-NEXT:           solidity.yul_block {
// CHECK-NEXT:             solidity.yul_block {
// CHECK-NEXT:             }
// CHECK-NEXT:           }
// CHECK-NEXT:         }
// CHECK-NEXT:       }
// CHECK-NEXT:     }
// CHECK-NEXT:   }
// CHECK-NEXT: }
// DBG: module {
// DBG-NEXT:   solidity.object @Foo {
// DBG-NEXT:     solidity.yul_block {
// DBG-NEXT:       solidity.yul_block {
// DBG-NEXT:         solidity.object @Foo_deployed {
// DBG-NEXT:           solidity.yul_block {
// DBG-NEXT:             solidity.yul_block {
// DBG-NEXT:             } loc(#loc2)
// DBG-NEXT:           } loc(#loc2)
// DBG-NEXT:         } loc(#loc0)
// DBG-NEXT:       } loc(#loc1)
// DBG-NEXT:     } loc(#loc1)
// DBG-NEXT:   } loc(#loc0)
// DBG-NEXT: } loc(#loc0)
// DBG-NEXT: #loc0 = loc(unknown)
// DBG-NEXT: #loc1 = loc({{.*}}:4:7)
// DBG-NEXT: #loc2 = loc({{.*}}:6:9)
