// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

function ret_42() returns (uint256) {
  return 42;
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: module {
// CHECK-NEXT:   sol.func @ret_42_8() -> ui256 attributes {state_mutability = #NonPayable} {
// CHECK-NEXT:     %c42_ui8 = sol.constant 42 : ui8 loc(#loc2)
// CHECK-NEXT:     %0 = sol.ext %c42_ui8 : ui8 to ui256 loc(#loc2)
// CHECK-NEXT:     sol.return %0 : ui256 loc(#loc3)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:3:9)
// CHECK-NEXT: #loc3 = loc({{.*}}:3:2)
// CHECK-EMPTY:
