// RUN: solc --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

contract C {
  struct S {
    uint256 ui;
    uint256[3] ui_1d;
  }

  function ui(S memory s) private returns (uint256) {
    return s.ui + s.ui_1d[2];
  }

  function malloc() private {
    S memory s;
  }
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Contract = #sol<ContractKind Contract>
// CHECK-NEXT: #NonPayable = #sol<StateMutability NonPayable>
// CHECK-NEXT: #loc3 = loc({{.*}}:8:14)
// CHECK-NEXT: module {
// CHECK-NEXT:   sol.contract @C_33 {
// CHECK-NEXT:     sol.func @ui_24(%arg0: !sol.struct<(ui256, !sol.array<3 x ui256, Memory>), Memory> loc({{.*}}:8:14)) -> ui256 attributes {state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.struct<(ui256, !sol.array<3 x ui256, Memory>), Memory>, Stack> loc(#loc3)
// CHECK-NEXT:       sol.store %arg0, %0 : !sol.struct<(ui256, !sol.array<3 x ui256, Memory>), Memory>, !sol.ptr<!sol.struct<(ui256, !sol.array<3 x ui256, Memory>), Memory>, Stack> loc(#loc3)
// CHECK-NEXT:       %c0_ui64 = sol.constant 0 : ui64 loc(#loc4)
// CHECK-NEXT:       %1 = sol.load %0 : !sol.ptr<!sol.struct<(ui256, !sol.array<3 x ui256, Memory>), Memory>, Stack>, !sol.struct<(ui256, !sol.array<3 x ui256, Memory>), Memory> loc(#loc4)
// CHECK-NEXT:       %2 = sol.gep %1, %c0_ui64 : !sol.struct<(ui256, !sol.array<3 x ui256, Memory>), Memory>, ui64, !sol.ptr<ui256, Memory> loc(#loc4)
// CHECK-NEXT:       %3 = sol.load %2 : !sol.ptr<ui256, Memory>, ui256 loc(#loc4)
// CHECK-NEXT:       %c1_ui64 = sol.constant 1 : ui64 loc(#loc5)
// CHECK-NEXT:       %4 = sol.load %0 : !sol.ptr<!sol.struct<(ui256, !sol.array<3 x ui256, Memory>), Memory>, Stack>, !sol.struct<(ui256, !sol.array<3 x ui256, Memory>), Memory> loc(#loc5)
// CHECK-NEXT:       %5 = sol.gep %4, %c1_ui64 : !sol.struct<(ui256, !sol.array<3 x ui256, Memory>), Memory>, ui64, !sol.array<3 x ui256, Memory> loc(#loc5)
// CHECK-NEXT:       %c2_ui8 = sol.constant 2 : ui8 loc(#loc6)
// CHECK-NEXT:       %6 = sol.gep %5, %c2_ui8 : !sol.array<3 x ui256, Memory>, ui8, !sol.ptr<ui256, Memory> loc(#loc5)
// CHECK-NEXT:       %7 = sol.load %6 : !sol.ptr<ui256, Memory>, ui256 loc(#loc5)
// CHECK-NEXT:       %8 = sol.cadd %3, %7 : ui256 loc(#loc4)
// CHECK-NEXT:       sol.return %8 : ui256 loc(#loc7)
// CHECK-NEXT:     } loc(#loc2)
// CHECK-NEXT:     sol.func @malloc_32() attributes {state_mutability = #NonPayable} {
// CHECK-NEXT:       %0 = sol.alloca : !sol.ptr<!sol.struct<(ui256, !sol.array<3 x ui256, Memory>), Memory>, Stack> loc(#loc9)
// CHECK-NEXT:       %1 = sol.malloc zero_init : !sol.struct<(ui256, !sol.array<3 x ui256, Memory>), Memory> loc(#loc9)
// CHECK-NEXT:       sol.store %1, %0 : !sol.struct<(ui256, !sol.array<3 x ui256, Memory>), Memory>, !sol.ptr<!sol.struct<(ui256, !sol.array<3 x ui256, Memory>), Memory>, Stack> loc(#loc9)
// CHECK-NEXT:       sol.return loc(#loc8)
// CHECK-NEXT:     } loc(#loc8)
// CHECK-NEXT:   } {interface_fns = [], kind = #Contract} loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc2 = loc({{.*}}:8:2)
// CHECK-NEXT: #loc4 = loc({{.*}}:9:11)
// CHECK-NEXT: #loc5 = loc({{.*}}:9:18)
// CHECK-NEXT: #loc6 = loc({{.*}}:9:26)
// CHECK-NEXT: #loc7 = loc({{.*}}:9:4)
// CHECK-NEXT: #loc8 = loc({{.*}}:12:2)
// CHECK-NEXT: #loc9 = loc({{.*}}:13:4)
// CHECK-EMPTY:
