// RUN: solc --mlir-action=print-std-mlir --mlir-target=evm --mmlir --mlir-print-debuginfo %s | FileCheck %s

function power(uint256 base, uint256 exponent) pure returns (uint256) {
  unchecked {
    return base ** exponent;
  }
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Prague = #sol<EvmVersion Prague>
// CHECK-NEXT: #loc2 = loc({{.*}}:2:15)
// CHECK-NEXT: #loc3 = loc({{.*}}:2:29)
// CHECK-NEXT: module attributes {sol.evm_version = #Prague} {
// CHECK-NEXT:   func.func @power_15(%arg0: i256 loc({{.*}}:2:15), %arg1: i256 loc({{.*}}:2:29)) -> i256 attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     %c1_i256 = arith.constant 1 : i256 loc(#loc)
// CHECK-NEXT:     %0 = llvm.alloca %c1_i256 x !llvm.ptr : (i256) -> !llvm.ptr loc(#loc2)
// CHECK-NEXT:     llvm.store %arg0, %0 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc2)
// CHECK-NEXT:     %1 = llvm.alloca %c1_i256 x !llvm.ptr : (i256) -> !llvm.ptr loc(#loc3)
// CHECK-NEXT:     llvm.store %arg1, %1 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc3)
// CHECK-NEXT:     %2 = llvm.load %0 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc4)
// CHECK-NEXT:     %3 = llvm.load %1 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc5)
// CHECK-NEXT:     %4 = "llvm.intrcall"(%2, %3) <{id = 3708 : i32, name = "evm.exp"}> : (i256, i256) -> i256 loc(#loc4)
// CHECK-NEXT:     return %4 : i256 loc(#loc6)
// CHECK-NEXT:   } loc(#loc1)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:2:0)
// CHECK-NEXT: #loc4 = loc({{.*}}:4:11)
// CHECK-NEXT: #loc5 = loc({{.*}}:4:19)
// CHECK-NEXT: #loc6 = loc({{.*}}:4:4)
// CHECK-EMPTY:
