// RUN: solc --strict-assembly --mlir-action=print-std-mlir --mlir-target=evm --mmlir --mlir-print-debuginfo %s | FileCheck %s

object "Test" {
  code {
    calldatacopy(0, calldataload(0), calldatasize())
  }
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: module {
// CHECK-NEXT:   func.func private @__entry() attributes {llvm.linkage = #llvm.linkage<external>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     %c0_i256 = arith.constant 0 : i256 loc(#loc1)
// CHECK-NEXT:     %c0_i256_0 = arith.constant 0 : i256 loc(#loc2)
// CHECK-NEXT:     %0 = llvm.inttoptr %c0_i256_0 : i256 to !llvm.ptr<2> loc(#loc3)
// CHECK-NEXT:     %1 = llvm.load %0 {alignment = 1 : i64} : !llvm.ptr<2> -> i256 loc(#loc3)
// CHECK-NEXT:     %2 = "llvm.intrcall"() <{id = 3213 : i32, name = "evm.calldatasize"}> : () -> i256 loc(#loc4)
// CHECK-NEXT:     %3 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc5)
// CHECK-NEXT:     %4 = llvm.inttoptr %1 : i256 to !llvm.ptr<2> loc(#loc5)
// CHECK-NEXT:     "llvm.intr.memcpy"(%3, %4, %2) <{isVolatile = false}> : (!llvm.ptr<1>, !llvm.ptr<2>, i256) -> () loc(#loc5)
// CHECK-NEXT:     llvm.unreachable loc(#loc)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:4:17)
// CHECK-NEXT: #loc2 = loc({{.*}}:4:33)
// CHECK-NEXT: #loc3 = loc({{.*}}:4:20)
// CHECK-NEXT: #loc4 = loc({{.*}}:4:37)
// CHECK-NEXT: #loc5 = loc({{.*}}:4:4)
// CHECK-EMPTY:
