// RUN: solc --strict-assembly --mlir-action=print-std-mlir --mlir-target=evm --mmlir --mlir-print-debuginfo %s | FileCheck %s

object "Test" {
  code {
    mstore(0, memoryguard(1))
    mstore(0, mload(1))
  }
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: module {
// CHECK-NEXT:   func.func private @__entry() attributes {llvm.linkage = #llvm.linkage<external>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     %c0_i256 = arith.constant 0 : i256 loc(#loc1)
// CHECK-NEXT:     %c1_i256 = arith.constant 1 : i256 loc(#loc2)
// CHECK-NEXT:     %0 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:     llvm.store %c1_i256, %0 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:     %c0_i256_0 = arith.constant 0 : i256 loc(#loc4)
// CHECK-NEXT:     %c1_i256_1 = arith.constant 1 : i256 loc(#loc5)
// CHECK-NEXT:     %1 = llvm.inttoptr %c1_i256_1 : i256 to !llvm.ptr<1> loc(#loc6)
// CHECK-NEXT:     %2 = llvm.load %1 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc6)
// CHECK-NEXT:     %3 = llvm.inttoptr %c0_i256_0 : i256 to !llvm.ptr<1> loc(#loc7)
// CHECK-NEXT:     llvm.store %2, %3 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc7)
// CHECK-NEXT:     llvm.unreachable loc(#loc)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:4:11)
// CHECK-NEXT: #loc2 = loc({{.*}}:4:14)
// CHECK-NEXT: #loc3 = loc({{.*}}:4:4)
// CHECK-NEXT: #loc4 = loc({{.*}}:5:11)
// CHECK-NEXT: #loc5 = loc({{.*}}:5:20)
// CHECK-NEXT: #loc6 = loc({{.*}}:5:14)
// CHECK-NEXT: #loc7 = loc({{.*}}:5:4)
// CHECK-EMPTY:
