// RUN: solc --strict-assembly --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

object "Test" {
  code {
    let a := mload(0)
    let b := mload(32)
    mstore(0, exp(a, b))
    return(0, 32)
  }
  object "Test_deployed" {
    code {}
  }
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Prague = #sol<EvmVersion Prague>
// CHECK-NEXT: module attributes {sol.evm_version = #Prague} {
// CHECK-NEXT:   yul.object @Test {
// CHECK-NEXT:     %c0_i256 = arith.constant 0 : i256 loc(#loc1)
// CHECK-NEXT:     %0 = yul.mload %c0_i256 loc(#loc2)
// CHECK-NEXT:     %c1_i256 = arith.constant 1 : i256 loc(#loc3)
// CHECK-NEXT:     %1 = llvm.alloca %c1_i256 x i256 {alignment = 32 : i64} : (i256) -> !llvm.ptr loc(#loc4)
// CHECK-NEXT:     llvm.store %0, %1 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc3)
// CHECK-NEXT:     %c32_i256 = arith.constant 32 : i256 loc(#loc5)
// CHECK-NEXT:     %2 = yul.mload %c32_i256 loc(#loc6)
// CHECK-NEXT:     %c1_i256_0 = arith.constant 1 : i256 loc(#loc7)
// CHECK-NEXT:     %3 = llvm.alloca %c1_i256_0 x i256 {alignment = 32 : i64} : (i256) -> !llvm.ptr loc(#loc8)
// CHECK-NEXT:     llvm.store %2, %3 {alignment = 32 : i64} : i256, !llvm.ptr loc(#loc7)
// CHECK-NEXT:     %c0_i256_1 = arith.constant 0 : i256 loc(#loc9)
// CHECK-NEXT:     %4 = llvm.load %1 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc10)
// CHECK-NEXT:     %5 = llvm.load %3 {alignment = 32 : i64} : !llvm.ptr -> i256 loc(#loc11)
// CHECK-NEXT:     %6 = yul.exp %4, %5 loc(#loc12)
// CHECK-NEXT:     yul.mstore %c0_i256_1, %6 loc(#loc13)
// CHECK-NEXT:     %c0_i256_2 = arith.constant 0 : i256 loc(#loc14)
// CHECK-NEXT:     %c32_i256_3 = arith.constant 32 : i256 loc(#loc15)
// CHECK-NEXT:     yul.return %c0_i256_2, %c32_i256_3 loc(#loc16)
// CHECK-NEXT:     yul.object @Test_deployed {
// CHECK-NEXT:     } loc(#loc)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:4:19)
// CHECK-NEXT: #loc2 = loc({{.*}}:4:13)
// CHECK-NEXT: #loc3 = loc({{.*}}:4:4)
// CHECK-NEXT: #loc4 = loc({{.*}}:4:8)
// CHECK-NEXT: #loc5 = loc({{.*}}:5:19)
// CHECK-NEXT: #loc6 = loc({{.*}}:5:13)
// CHECK-NEXT: #loc7 = loc({{.*}}:5:4)
// CHECK-NEXT: #loc8 = loc({{.*}}:5:8)
// CHECK-NEXT: #loc9 = loc({{.*}}:6:11)
// CHECK-NEXT: #loc10 = loc({{.*}}:6:18)
// CHECK-NEXT: #loc11 = loc({{.*}}:6:21)
// CHECK-NEXT: #loc12 = loc({{.*}}:6:14)
// CHECK-NEXT: #loc13 = loc({{.*}}:6:4)
// CHECK-NEXT: #loc14 = loc({{.*}}:7:11)
// CHECK-NEXT: #loc15 = loc({{.*}}:7:14)
// CHECK-NEXT: #loc16 = loc({{.*}}:7:4)
// CHECK-EMPTY:
