// RUN: solc --strict-assembly --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

object "Test" {
  code {
    extcodecopy(0xaaaaaaaa, 0, 4, 128)
    return(0, 128)
  }
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Prague = #sol<EvmVersion Prague>
// CHECK-NEXT: module attributes {sol.evm_version = #Prague} {
// CHECK-NEXT:   yul.object @Test {
// CHECK-NEXT:     %c2863311530_i256 = arith.constant 2863311530 : i256 loc(#loc1)
// CHECK-NEXT:     %c0_i256 = arith.constant 0 : i256 loc(#loc2)
// CHECK-NEXT:     %c4_i256 = arith.constant 4 : i256 loc(#loc3)
// CHECK-NEXT:     %c128_i256 = arith.constant 128 : i256 loc(#loc4)
// CHECK-NEXT:     yul.extcodecopy %c2863311530_i256, %c0_i256, %c4_i256, %c128_i256 loc(#loc5)
// CHECK-NEXT:     %c0_i256_0 = arith.constant 0 : i256 loc(#loc6)
// CHECK-NEXT:     %c128_i256_1 = arith.constant 128 : i256 loc(#loc7)
// CHECK-NEXT:     yul.return %c0_i256_0, %c128_i256_1 loc(#loc8)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:4:16)
// CHECK-NEXT: #loc2 = loc({{.*}}:4:28)
// CHECK-NEXT: #loc3 = loc({{.*}}:4:31)
// CHECK-NEXT: #loc4 = loc({{.*}}:4:34)
// CHECK-NEXT: #loc5 = loc({{.*}}:4:4)
// CHECK-NEXT: #loc6 = loc({{.*}}:5:11)
// CHECK-NEXT: #loc7 = loc({{.*}}:5:14)
// CHECK-NEXT: #loc8 = loc({{.*}}:5:4)
// CHECK-EMPTY:
