// RUN: solc --strict-assembly --mlir-action=print-init --mmlir --mlir-print-debuginfo %s | FileCheck %s

object "Test" {
  code {
    mstore(0, number())
    return(0, 32)
  }
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Prague = #sol<EvmVersion Prague>
// CHECK-NEXT: module attributes {sol.evm_version = #Prague} {
// CHECK-NEXT:   yul.object @Test {
// CHECK-NEXT:     %c0_i256 = arith.constant 0 : i256 loc(#loc1)
// CHECK-NEXT:     %0 = yul.number loc(#loc2)
// CHECK-NEXT:     yul.mstore %c0_i256, %0 loc(#loc3)
// CHECK-NEXT:     %c0_i256_0 = arith.constant 0 : i256 loc(#loc4)
// CHECK-NEXT:     %c32_i256 = arith.constant 32 : i256 loc(#loc5)
// CHECK-NEXT:     yul.return %c0_i256_0, %c32_i256 loc(#loc6)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:4:11)
// CHECK-NEXT: #loc2 = loc({{.*}}:4:14)
// CHECK-NEXT: #loc3 = loc({{.*}}:4:4)
// CHECK-NEXT: #loc4 = loc({{.*}}:5:11)
// CHECK-NEXT: #loc5 = loc({{.*}}:5:14)
// CHECK-NEXT: #loc6 = loc({{.*}}:5:4)
// CHECK-EMPTY:
