// RUN: solc --strict-assembly --mlir-action=print-init --mmlir --mlir-print-debuginfo --mlir-target=eravm %s | FileCheck %s

object "Test" {
  code {
    calldatacopy(0, 1, 32)
    return(0, 0)
  }
  object "Test_deployed" {
    code {
      calldatacopy(0, 1, 32)
      return(0, 0)
    }
  }
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: module {
// CHECK-NEXT:   sol.object @Test {
// CHECK-NEXT:     %c0_i256 = arith.constant 0 : i256 loc(#loc1)
// CHECK-NEXT:     %c1_i256 = arith.constant 1 : i256 loc(#loc2)
// CHECK-NEXT:     %c32_i256 = arith.constant 32 : i256 loc(#loc3)
// CHECK-NEXT:     sol.calldatacopy %c0_i256, %c1_i256, %c32_i256 loc(#loc4)
// CHECK-NEXT:     %c0_i256_0 = arith.constant 0 : i256 loc(#loc5)
// CHECK-NEXT:     %c0_i256_1 = arith.constant 0 : i256 loc(#loc6)
// CHECK-NEXT:     sol.builtin_ret %c0_i256_0, %c0_i256_1 loc(#loc7)
// CHECK-NEXT:     sol.object @Test_deployed {
// CHECK-NEXT:       %c0_i256_2 = arith.constant 0 : i256 loc(#loc8)
// CHECK-NEXT:       %c1_i256_3 = arith.constant 1 : i256 loc(#loc9)
// CHECK-NEXT:       %c32_i256_4 = arith.constant 32 : i256 loc(#loc10)
// CHECK-NEXT:       sol.calldatacopy %c0_i256_2, %c1_i256_3, %c32_i256_4 loc(#loc11)
// CHECK-NEXT:       %c0_i256_5 = arith.constant 0 : i256 loc(#loc12)
// CHECK-NEXT:       %c0_i256_6 = arith.constant 0 : i256 loc(#loc13)
// CHECK-NEXT:       sol.builtin_ret %c0_i256_5, %c0_i256_6 loc(#loc14)
// CHECK-NEXT:     } loc(#loc)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:4:17)
// CHECK-NEXT: #loc2 = loc({{.*}}:4:20)
// CHECK-NEXT: #loc3 = loc({{.*}}:4:23)
// CHECK-NEXT: #loc4 = loc({{.*}}:4:4)
// CHECK-NEXT: #loc5 = loc({{.*}}:5:11)
// CHECK-NEXT: #loc6 = loc({{.*}}:5:14)
// CHECK-NEXT: #loc7 = loc({{.*}}:5:4)
// CHECK-NEXT: #loc8 = loc({{.*}}:9:19)
// CHECK-NEXT: #loc9 = loc({{.*}}:9:22)
// CHECK-NEXT: #loc10 = loc({{.*}}:9:25)
// CHECK-NEXT: #loc11 = loc({{.*}}:9:6)
// CHECK-NEXT: #loc12 = loc({{.*}}:10:13)
// CHECK-NEXT: #loc13 = loc({{.*}}:10:16)
// CHECK-NEXT: #loc14 = loc({{.*}}:10:6)
// CHECK-EMPTY:
