// RUN: solc --strict-assembly --mlir-action=print-init --mmlir --mlir-print-debuginfo --mlir-target=eravm %s | FileCheck %s

object "Test" {
  code {
    return(0, codesize())
  }
  object "Test_deployed" {
    code {
      return(0, codesize())
    }
  }
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: module {
// CHECK-NEXT:   sol.object @Test {
// CHECK-NEXT:     %c0_i256 = arith.constant 0 : i256 loc(#loc1)
// CHECK-NEXT:     %0 = sol.codesize loc(#loc2)
// CHECK-NEXT:     sol.builtin_ret %c0_i256, %0 loc(#loc3)
// CHECK-NEXT:     sol.object @Test_deployed {
// CHECK-NEXT:       %c0_i256_0 = arith.constant 0 : i256 loc(#loc4)
// CHECK-NEXT:       %1 = sol.codesize loc(#loc5)
// CHECK-NEXT:       sol.builtin_ret %c0_i256_0, %1 loc(#loc6)
// CHECK-NEXT:     } loc(#loc)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:0:36)
// CHECK-NEXT: #loc2 = loc({{.*}}:0:39)
// CHECK-NEXT: #loc3 = loc({{.*}}:0:29)
// CHECK-NEXT: #loc4 = loc({{.*}}:0:108)
// CHECK-NEXT: #loc5 = loc({{.*}}:0:111)
// CHECK-NEXT: #loc6 = loc({{.*}}:0:101)
// CHECK-EMPTY:
