// RUN: solc --strict-assembly --mlir-action=print-init --mmlir --mlir-print-debuginfo --mlir-target=eravm %s | FileCheck %s

object "Test" {
  code {
    return(keccak256(0, 0x40), 0)
  }
  object "Test_deployed" {
    code {
      return(keccak256(0, 0x40), 0)
    }
  }
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: module {
// CHECK-NEXT:   sol.object @Test {
// CHECK-NEXT:     %c0_i256 = arith.constant 0 : i256 loc(#loc1)
// CHECK-NEXT:     %c64_i256 = arith.constant 64 : i256 loc(#loc2)
// CHECK-NEXT:     %0 = sol.keccak256 %c0_i256, %c64_i256 loc(#loc3)
// CHECK-NEXT:     %c0_i256_0 = arith.constant 0 : i256 loc(#loc4)
// CHECK-NEXT:     sol.builtin_ret %0, %c0_i256_0 loc(#loc5)
// CHECK-NEXT:     sol.object @Test_deployed {
// CHECK-NEXT:       %c0_i256_1 = arith.constant 0 : i256 loc(#loc6)
// CHECK-NEXT:       %c64_i256_2 = arith.constant 64 : i256 loc(#loc7)
// CHECK-NEXT:       %1 = sol.keccak256 %c0_i256_1, %c64_i256_2 loc(#loc8)
// CHECK-NEXT:       %c0_i256_3 = arith.constant 0 : i256 loc(#loc9)
// CHECK-NEXT:       sol.builtin_ret %1, %c0_i256_3 loc(#loc10)
// CHECK-NEXT:     } loc(#loc)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:0:54)
// CHECK-NEXT: #loc2 = loc({{.*}}:0:57)
// CHECK-NEXT: #loc3 = loc({{.*}}:0:44)
// CHECK-NEXT: #loc4 = loc({{.*}}:0:64)
// CHECK-NEXT: #loc5 = loc({{.*}}:0:37)
// CHECK-NEXT: #loc6 = loc({{.*}}:3:8)
// CHECK-NEXT: #loc7 = loc({{.*}}:4:2)
// CHECK-NEXT: #loc8 = loc({{.*}}:2:14)
// CHECK-NEXT: #loc9 = loc({{.*}}:4:9)
// CHECK-NEXT: #loc10 = loc({{.*}}:2:7)
// CHECK-EMPTY:
