// RUN: solc --strict-assembly --mlir-action=print-init --mmlir --mlir-print-debuginfo --mlir-target=eravm %s | FileCheck %s

object "Test" {
  code {
    mcopy(42, 82, 3)
    return(0, 0)
  }
  object "Test_deployed" {
    code {
      mcopy(42, 82, 3)
      return(0, 0)
    }
  }
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: module {
// CHECK-NEXT:   sol.object @Test {
// CHECK-NEXT:     %c42_i256 = arith.constant 42 : i256 loc(#loc1)
// CHECK-NEXT:     %c82_i256 = arith.constant 82 : i256 loc(#loc2)
// CHECK-NEXT:     %c3_i256 = arith.constant 3 : i256 loc(#loc3)
// CHECK-NEXT:     sol.mcopy %c42_i256, %c82_i256, %c3_i256 loc(#loc4)
// CHECK-NEXT:     %c0_i256 = arith.constant 0 : i256 loc(#loc5)
// CHECK-NEXT:     %c0_i256_0 = arith.constant 0 : i256 loc(#loc6)
// CHECK-NEXT:     sol.builtin_ret %c0_i256, %c0_i256_0 loc(#loc7)
// CHECK-NEXT:     sol.object @Test_deployed {
// CHECK-NEXT:       %c42_i256_1 = arith.constant 42 : i256 loc(#loc8)
// CHECK-NEXT:       %c82_i256_2 = arith.constant 82 : i256 loc(#loc9)
// CHECK-NEXT:       %c3_i256_3 = arith.constant 3 : i256 loc(#loc10)
// CHECK-NEXT:       sol.mcopy %c42_i256_1, %c82_i256_2, %c3_i256_3 loc(#loc11)
// CHECK-NEXT:       %c0_i256_4 = arith.constant 0 : i256 loc(#loc12)
// CHECK-NEXT:       %c0_i256_5 = arith.constant 0 : i256 loc(#loc13)
// CHECK-NEXT:       sol.builtin_ret %c0_i256_4, %c0_i256_5 loc(#loc14)
// CHECK-NEXT:     } loc(#loc)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:0:55)
// CHECK-NEXT: #loc2 = loc({{.*}}:0:59)
// CHECK-NEXT: #loc3 = loc({{.*}}:0:63)
// CHECK-NEXT: #loc4 = loc({{.*}}:0:49)
// CHECK-NEXT: #loc5 = loc({{.*}}:0:85)
// CHECK-NEXT: #loc6 = loc({{.*}}:0:88)
// CHECK-NEXT: #loc7 = loc({{.*}}:0:78)
// CHECK-NEXT: #loc8 = loc({{.*}}:5:15)
// CHECK-NEXT: #loc9 = loc({{.*}}:6:2)
// CHECK-NEXT: #loc10 = loc({{.*}}:7:2)
// CHECK-NEXT: #loc11 = loc({{.*}}:5:9)
// CHECK-NEXT: #loc12 = loc({{.*}}:8:1)
// CHECK-NEXT: #loc13 = loc({{.*}}:8:4)
// CHECK-NEXT: #loc14 = loc({{.*}}:7:21)
// CHECK-EMPTY:
