// RUN: solc --strict-assembly --mlir-action=print-init --mmlir --mlir-print-debuginfo --mlir-target=eravm %s | FileCheck %s

object "Test" {
  code {
    sstore(0, 10)
    return(0, 0)
  }
  object "Test_deployed" {
    code {
      sstore(0, 20)
      return(0, 0)
    }
  }
}

// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: module {
// CHECK-NEXT:   sol.object @Test {
// CHECK-NEXT:     %c0_i256 = arith.constant 0 : i256 loc(#loc1)
// CHECK-NEXT:     %c10_i256 = arith.constant 10 : i256 loc(#loc2)
// CHECK-NEXT:     sol.sstore %c0_i256, %c10_i256 loc(#loc3)
// CHECK-NEXT:     %c0_i256_0 = arith.constant 0 : i256 loc(#loc4)
// CHECK-NEXT:     %c0_i256_1 = arith.constant 0 : i256 loc(#loc5)
// CHECK-NEXT:     sol.builtin_ret %c0_i256_0, %c0_i256_1 loc(#loc6)
// CHECK-NEXT:     sol.object @Test_deployed {
// CHECK-NEXT:       %c0_i256_2 = arith.constant 0 : i256 loc(#loc7)
// CHECK-NEXT:       %c20_i256 = arith.constant 20 : i256 loc(#loc8)
// CHECK-NEXT:       sol.sstore %c0_i256_2, %c20_i256 loc(#loc9)
// CHECK-NEXT:       %c0_i256_3 = arith.constant 0 : i256 loc(#loc10)
// CHECK-NEXT:       %c0_i256_4 = arith.constant 0 : i256 loc(#loc11)
// CHECK-NEXT:       sol.builtin_ret %c0_i256_3, %c0_i256_4 loc(#loc12)
// CHECK-NEXT:     } loc(#loc)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:0:56)
// CHECK-NEXT: #loc2 = loc({{.*}}:0:59)
// CHECK-NEXT: #loc3 = loc({{.*}}:0:49)
// CHECK-NEXT: #loc4 = loc({{.*}}:0:82)
// CHECK-NEXT: #loc5 = loc({{.*}}:0:85)
// CHECK-NEXT: #loc6 = loc({{.*}}:0:75)
// CHECK-NEXT: #loc7 = loc({{.*}}:5:16)
// CHECK-NEXT: #loc8 = loc({{.*}}:6:2)
// CHECK-NEXT: #loc9 = loc({{.*}}:5:9)
// CHECK-NEXT: #loc10 = loc({{.*}}:7:25)
// CHECK-NEXT: #loc11 = loc({{.*}}:8:1)
// CHECK-NEXT: #loc12 = loc({{.*}}:7:18)
// CHECK-EMPTY:
