// RUN: solc --strict-assembly --mlir-action=print-std-mlir --mlir-target=evm --mmlir --mlir-print-debuginfo %s | FileCheck %s

object "Test" {
  code {
    mstore(0, signextend(mload(0), mload(32)))
    return(0, 32)
  }
}
// NOTE: Assertions have been autogenerated by test/updFileCheckTest.py
// CHECK: #Prague = #sol<EvmVersion Prague>
// CHECK-NEXT: module @Test attributes {sol.evm_version = #Prague} {
// CHECK-NEXT:   func.func @".unreachable"() attributes {llvm.linkage = #llvm.linkage<private>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     llvm.unreachable loc(#loc1)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT:   func.func @__entry() attributes {llvm.linkage = #llvm.linkage<external>, passthrough = ["nofree", "null_pointer_is_valid"]} {
// CHECK-NEXT:     %c32_i256 = arith.constant 32 : i256 loc(#loc)
// CHECK-NEXT:     %c0_i256 = arith.constant 0 : i256 loc(#loc)
// CHECK-NEXT:     %0 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc2)
// CHECK-NEXT:     %1 = llvm.load %0 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc2)
// CHECK-NEXT:     %2 = llvm.inttoptr %c32_i256 : i256 to !llvm.ptr<1> loc(#loc3)
// CHECK-NEXT:     %3 = llvm.load %2 {alignment = 1 : i64} : !llvm.ptr<1> -> i256 loc(#loc3)
// CHECK-NEXT:     %4 = "llvm.intrcall"(%1, %3) <{id = 3745 : i32, name = "evm.signextend"}> : (i256, i256) -> i256 loc(#loc4)
// CHECK-NEXT:     %5 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc5)
// CHECK-NEXT:     llvm.store %4, %5 {alignment = 1 : i64} : i256, !llvm.ptr<1> loc(#loc5)
// CHECK-NEXT:     %6 = llvm.inttoptr %c0_i256 : i256 to !llvm.ptr<1> loc(#loc1)
// CHECK-NEXT:     "llvm.intrcall"(%6, %c32_i256) <{id = 3735 : i32, name = "evm.return"}> : (!llvm.ptr<1>, i256) -> () loc(#loc1)
// CHECK-NEXT:     call @".unreachable"() : () -> () loc(#loc1)
// CHECK-NEXT:     llvm.unreachable loc(#loc)
// CHECK-NEXT:   } loc(#loc)
// CHECK-NEXT: } loc(#loc)
// CHECK-NEXT: #loc = loc(unknown)
// CHECK-NEXT: #loc1 = loc({{.*}}:5:4)
// CHECK-NEXT: #loc2 = loc({{.*}}:4:25)
// CHECK-NEXT: #loc3 = loc({{.*}}:4:35)
// CHECK-NEXT: #loc4 = loc({{.*}}:4:14)
// CHECK-NEXT: #loc5 = loc({{.*}}:4:4)
// CHECK-EMPTY:
